### ISSUE TITLE
Performance improvements (PageSpeed)

### ISSUE THREAD

**Issue by Dsibe** [lepture/shibuya#51] opened 2024-05-28 21:29 UTC
Amazing theme - looks really nice! I just ran a quick scan from a random page on pagespeed, and sadly, it seems like the performance of pages could be improved, [see page speed report analysis](https://pagespeed.web.dev/analysis/https-shibuya-lepture-com-writing-api/9mz43k3jw3?form_factor=mobile). SEO is really important for documentation websites, - and pagespeed score plays a huge role in ranking. I am sure that improving the performance of Shibuya would be really appreciated by many devs. 

Unfortunately, there are not so many good-looking themes for Sphinx, and seeing a new one is exciting; so, thank you for creating such a nice theme!

**Comment by lepture** [comment] 2024-05-29 03:19
I don’t think it can be fixed by the theme. Most of the issues pagespeed provided are not caused by the theme. Some of theme are caused by sphinx extensions, some are caused by the documentation itself.

And also, if you check the performance for desktop, it is good.

**Comment by lepture** [comment] 2024-05-30 05:32
Here is an example for shibuya theme with less sphinx extensions:

https://pagespeed.web.dev/analysis/https-jose-authlib-org-en/kcllsbfbai?form_factor=mobile

If you know how to fix **Largest Contentful Paint** issue, that would be great.

**Closed** 2024-07-05 10:26 UTC
